### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by paulrehkugler** [Yelp/cocoapods-readonly#3]
When running `pod install` using cocoapods 3.9, I receive this error:

```
---------------------------------------------
Error loading the plugin with path `/Library/Ruby/Gems/2.0.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods_plugin.rb`.

NameError - undefined method `run_pre_install_hooks' for class `Pod::Installer'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods-readonly/toggle_readonly.rb:21:in `alias_method'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods-readonly/toggle_readonly.rb:21:in `<class:Installer>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods-readonly/toggle_readonly.rb:2:in `<module:Pod>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods-readonly/toggle_readonly.rb:1:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods_plugin.rb:1:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------
```

**Comment by segiddins** [comment]
I believe this plugin has been deprecated as the functionality is now in cocoapods itself.

**Comment by benasher44** [comment]
@segiddins @paulrehkugler that's correct. As of 0.37.0, this functionality is built into cocoapods. Filed #4 regarding this

**Comment by paulrehkugler** [comment]
Huh, cool.
